export const sample_foods = [
    {
      id: '1',
      name: 'Pizza',
      cookTime: '10-20',
      price: 200,
      favorite: false,
      origins: ['italy'],
      stars: 4.5,
      imageUrl: '/foods/food-1.jpg',
      tags: ['FastFood', 'Pizza', 'Lunch'],
    },
    {
      id: '2',
      name: 'Spring Roll',
      price: 60,
      cookTime: '20-30',
      favorite: true,
      origins: ['persia', 'middle east', 'china'],
      stars: 5,
      imageUrl: '/foods/food-2.jpg',
      tags: ['Fast Food', 'Snacks','Fry'],
    },
    {
      id: '3',
      name: 'Hamburger',
      price: 130,
      cookTime: '10-15',
      favorite: false,
      origins: ['germany', 'us'],
      stars: 3.5,
      imageUrl: '/foods/food-4.jpg',
      tags: ['FastFood', 'Hamburger'],
    },
    {
      id: '4',
      name: 'Momos',
      price: 60,
      cookTime: '15-20',
      favorite: true,
      origins: ['nepal', 'china'],
      stars: 3,
      imageUrl: '/foods/food-3.jpg',
      tags: ['FastFood', 'Fry','Steamed'],
    },
    {
      id: '5',
      name: 'Raj Kachori',
      price: 80,
      cookTime: '5-10',
      favorite: false,
      origins: ['india', 'asia'],
      stars: 3.5,
      imageUrl: '/foods/food-5.jpg',
      tags: ['SlowFood', 'Chaat'],
    },
    {
      id: '6',
      name: 'Rajma Chawal',
      price: 50,
      cookTime: '40-50',
      favorite: false,
      origins: ['india'],
      stars: 4.0,
      imageUrl: '/foods/food-6.jpg',
      tags: ['SlowFood', 'Lunch'],
    },
  ];
  export const sample_tags = [
    { name: 'All', count: 6 },
    { name: 'FastFood', count: 4 },
    { name: 'Pizza', count: 1 },
    { name: 'Lunch', count: 2 },
    { name: 'SlowFood', count: 2 },
    { name: 'Hamburger', count: 1 },
    { name: 'Fry', count: 2 },
  ];
  export const sample_users = [
    {
      id: 1,
      name: 'Uday Chandan',
      email: 'uday@gmail.com',
      password: '12345',
      address: 'Nangal India',
      isAdmin: true,
    },
    {
      id: 2,
      name: 'Yoshank Goyal',
      email: 'yoshank@gmail.com',
      password: '12345',
      address: 'Panipat India',
      isAdmin: false,
    },
  ];